// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnMNWJQMJcQ31bYYwDj8nA2kE58KXmQOE',
    appId: '1:580091463076:web:b599cdca93ed5fa3efad31',
    messagingSenderId: '580091463076',
    projectId: 'capstoneproject-f5551',
    authDomain: 'capstoneproject-f5551.firebaseapp.com',
    storageBucket: 'capstoneproject-f5551.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvYTndDpmc4SrBEISEWvIlBkI8D5zHDOI',
    appId: '1:580091463076:android:cec29d0f4e559891efad31',
    messagingSenderId: '580091463076',
    projectId: 'capstoneproject-f5551',
    storageBucket: 'capstoneproject-f5551.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_wCLSkJk5_ji86YYGH6eo1AuzZVwLZEY',
    appId: '1:580091463076:ios:32de9308413c6f2defad31',
    messagingSenderId: '580091463076',
    projectId: 'capstoneproject-f5551',
    storageBucket: 'capstoneproject-f5551.appspot.com',
    iosBundleId: 'com.example.capstoneProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_wCLSkJk5_ji86YYGH6eo1AuzZVwLZEY',
    appId: '1:580091463076:ios:663ca0c937195215efad31',
    messagingSenderId: '580091463076',
    projectId: 'capstoneproject-f5551',
    storageBucket: 'capstoneproject-f5551.appspot.com',
    iosBundleId: 'com.example.capstoneProject.RunnerTests',
  );
}
